### ISSUE TITLE
OTP issues

### ISSUE THREAD

**Issue by Shivank98** [PyJaipur/SoA#29]
OTP link come as **https://soa.pyjaipur.org**/otp?q=xxxxxxxxxxxxxxxxxxxxxxxxxxxx from the heroku link of SoA. 
soa.pyjaupur is still there. should it be like that or pyjaipur-soa.herokuapp.com also both OTPs doesn't work.

**Comment by theSage21** [comment]
Thanks for the catch @Shivank98 

Our current architecture is a little strange and this was a result of that.

1. We maintain a netlify app from the `netlify` branch of this project [which specifies a redirect](https://github.com/PyJaipur/SoA/blob/netlify/netlify.toml) from soa.pyjaipur.org to our heroku app.
2. This way we can maintain full HTTPS without any costs
3. The domain redirect, however, strips the query parameters while redirecting. That's why we were losing the otp tokens.

The link in the email is generated using the env variable BASE_DOMAIN. I've corrected this in our app and otps should now work normally.

**Comment by Shivank98** [comment]
Looks good. I missed that.
